{"logradouro": "Rua Almirante Tamandar\u00e9", "numero": 678, "bairro": "Floresta", "cidade": "Porto Alegre", "estado": "RS", "area": 150, "quartos": 3, "banheiros": 3, "vagas": 0, "preco": 470000}
{"logradouro": "Rua Quintino Bocai\u00fava", "numero": 411, "bairro": "Moinhos de Vento", "cidade": "Porto Alegre", "estado": "RS", "area": 48, "quartos": 1, "banheiros": 1, "vagas": 1, "preco": 399000}
{"logradouro": "Rua Guilherme Alves", "numero": 391, "bairro": "Jardim Bot\u00e2nico", "cidade": "Porto Alegre", "estado": "RS", "area": 71, "quartos": 2, "banheiros": 2, "vagas": 1, "preco": 470000}
{"logradouro": "Rua Teot\u00f4nia", "numero": 300, "bairro": "Camaqu\u00e3", "cidade": "Porto Alegre", "estado": "RS", "area": 72, "quartos": 3, "banheiros": 2, "vagas": 1, "preco": 429900}
{"logradouro": "Rua Doutor Veridiano Farias", "numero": 46, "bairro": "Petr\u00f3polis", "cidade": "Porto Alegre", "estado": "RS", "area": 88, "quartos": 3, "banheiros": 2, "vagas": 2, "preco": 890000}
{"logradouro": "Rua Ant\u00f4nio Divan", "numero": 409, "bairro": "Teres\u00f3polis", "cidade": "Porto Alegre", "estado": "RS", "area": 72, "quartos": 2, "banheiros": 1, "vagas": 1, "preco": 229000}
{"logradouro": "Rua Ad\u00e3o Baino", "numero": 133, "bairro": "Cristo Redentor", "cidade": "Porto Alegre", "estado": "RS", "area": 80, "quartos": 2, "banheiros": 1, "vagas": 1, "preco": 270000}
{"logradouro": "Rua Carlos Von Koseritz", "numero": 865, "bairro": "Higien\u00f3polis", "cidade": "Porto Alegre", "estado": "RS", "area": 108, "quartos": 3, "banheiros": 3, "vagas": 2, "preco": 749000}
{"logradouro": "Rua Professor Cristiano Fischer", "numero": 1216, "bairro": "Petr\u00f3polis", "cidade": "Porto Alegre", "estado": "RS", "area": 46, "quartos": 1, "banheiros": 1, "vagas": 1, "preco": 235000}
{"logradouro": "Rua Abram Goldsztein", "numero": 446, "bairro": "Jardim Carvalho", "cidade": "Porto Alegre", "estado": "RS", "area": 58, "quartos": 2, "banheiros": 1, "vagas": 1, "preco": 290000}
{"logradouro": "Rua Abram Goldsztein", "numero": 250, "bairro": "Jardim Carvalho", "cidade": "Porto Alegre", "estado": "RS", "area": 58, "quartos": 2, "banheiros": 1, "vagas": 0, "preco": 210000}
{"logradouro": "Avenida Prot\u00e1sio Alves", "numero": 9277, "bairro": "Morro Santana", "cidade": "Porto Alegre", "estado": "RS", "area": 47, "quartos": 2, "banheiros": 1, "vagas": 1, "preco": 230000}
{"logradouro": "Rua Jari", "numero": 740, "bairro": "Passo D areia", "cidade": "Porto Alegre", "estado": "RS", "area": 75, "quartos": 3, "banheiros": 2, "vagas": 2, "preco": 589000}
{"logradouro": "Avenida Bento Gon\u00e7alves", "numero": 205, "bairro": "Azenha", "cidade": "Porto Alegre", "estado": "RS", "area": 56, "quartos": 2, "banheiros": 2, "vagas": 1, "preco": 346800}
{"logradouro": "Rua Bispo William Thomas", "numero": 200, "bairro": "Teres\u00f3polis", "cidade": "Porto Alegre", "estado": "RS", "area": 93, "quartos": 3, "banheiros": 2, "vagas": 1, "preco": 500000}
{"logradouro": "Rua Filad\u00e9lfia", "numero": 169, "bairro": "S\u00e3o Jo\u00e3o", "cidade": "Porto Alegre", "estado": "RS", "area": 115, "quartos": 3, "banheiros": 3, "vagas": 2, "preco": 890000}
{"logradouro": "Rua Lasar Segall", "numero": 570, "bairro": "S\u00e3o Sebasti\u00e3o", "cidade": "Porto Alegre", "estado": "RS", "area": 40, "quartos": 1, "banheiros": 1, "vagas": 0, "preco": 110000}
{"logradouro": "Rua Doutor Carlos Renato R. Fonseca", "numero": 125, "bairro": "Jardim It\u00fa Sabar\u00e1", "cidade": "Porto Alegre", "estado": "RS", "area": 92, "quartos": 3, "banheiros": 2, "vagas": 2, "preco": 680000}
{"logradouro": "Rua D\u00e1rio Totta", "numero": 514, "bairro": "Teres\u00f3polis", "cidade": "Porto Alegre", "estado": "RS", "area": 70, "quartos": 2, "banheiros": 1, "vagas": 1, "preco": 215000}
{"logradouro": "Rua Ad\u00e3o Baino", "numero": 261, "bairro": "Cristo Redentor", "cidade": "Porto Alegre", "estado": "RS", "area": 61, "quartos": 2, "banheiros": 2, "vagas": 0, "preco": 399000}
{"logradouro": "Travessa Escobar", "numero": 193, "bairro": "Camaqu\u00e3", "cidade": "Porto Alegre", "estado": "RS", "area": 62, "quartos": 2, "banheiros": 2, "vagas": 1, "preco": 375000}
{"logradouro": "Rua Costa", "numero": 444, "bairro": "Menino Deus", "cidade": "Porto Alegre", "estado": "RS", "area": 98, "quartos": 3, "banheiros": 3, "vagas": 2, "preco": 798000}
{"logradouro": "Avenida General Barreto Viana", "numero": 1065, "bairro": "Ch\u00e1cara das Pedras", "cidade": "Porto Alegre", "estado": "RS", "area": 72, "quartos": 3, "banheiros": 2, "vagas": 1, "preco": 395000}
{"logradouro": "Rua Valdir Ant\u00f4nio Lopes", "numero": 199, "bairro": "Tr\u00eas Figueiras", "cidade": "Porto Alegre", "estado": "RS", "area": 38, "quartos": 1, "banheiros": 1, "vagas": 1, "preco": 480000}
{"logradouro": "Avenida Coronel Marcos", "numero": 500, "bairro": "Pedra Redonda", "cidade": "Porto Alegre", "estado": "RS", "area": 231, "quartos": 4, "banheiros": 4, "vagas": 3, "preco": 695000}
{"logradouro": "Rua Jos\u00e9 do Patroc\u00ednio", "numero": 913, "bairro": "Cidade Baixa", "cidade": "Porto Alegre", "estado": "RS", "area": 62, "quartos": 2, "banheiros": 2, "vagas": 2, "preco": 595000}
{"logradouro": "Rua Vig\u00e1rio Jos\u00e9 In\u00e1cio", "numero": 506, "bairro": "Centro Hist\u00f3rico", "cidade": "Porto Alegre", "estado": "RS", "area": 55, "quartos": 1, "banheiros": 1, "vagas": 0, "preco": 198000}
{"logradouro": "Rua Monsenhor Veras", "numero": 237, "bairro": "Santana", "cidade": "Porto Alegre", "estado": "RS", "area": 60, "quartos": 2, "banheiros": 1, "vagas": 1, "preco": 370000}
{"logradouro": "Rua Atan\u00e1sio Belmonte", "numero": 175, "bairro": "Boa Vista", "cidade": "Porto Alegre", "estado": "RS", "area": 84, "quartos": 3, "banheiros": 2, "vagas": 1, "preco": 500000}
{"logradouro": "Avenida Professor Oscar Pereira", "numero": 1207, "bairro": "Azenha", "cidade": "Porto Alegre", "estado": "RS", "area": 88, "quartos": 2, "banheiros": 1, "vagas": 1, "preco": 290000}
{"logradouro": "Avenida Baltazar de Oliveira Garcia", "numero": 2396, "bairro": "Costa E Silva", "cidade": "Porto Alegre", "estado": "RS", "area": 42, "quartos": 2, "banheiros": 1, "vagas": 1, "preco": 198000}
{"logradouro": "Rua Professor Joaber Pereira", "numero": 80, "bairro": "Sarandi", "cidade": "Porto Alegre", "estado": "RS", "area": 53, "quartos": 2, "banheiros": 1, "vagas": 1, "preco": 279000}
{"logradouro": "Rua Tenente Ary Tarrago", "numero": 3095, "bairro": "Jardim It\u00fa Sabar\u00e1", "cidade": "Porto Alegre", "estado": "RS", "area": 51, "quartos": 2, "banheiros": 2, "vagas": 1, "preco": 239000}
{"logradouro": "Rua D\u00e1rio Pederneiras", "numero": 145, "bairro": "Petr\u00f3polis", "cidade": "Porto Alegre", "estado": "RS", "area": 106, "quartos": 3, "banheiros": 2, "vagas": 2, "preco": 870000}
{"logradouro": "Avenida Prot\u00e1sio Alves", "numero": 9277, "bairro": "Alto Petr\u00f3polis", "cidade": "Porto Alegre", "estado": "RS", "area": 46, "quartos": 2, "banheiros": 1, "vagas": 1, "preco": 220000}
{"logradouro": "Avenida Padre Cacique", "numero": 266, "bairro": "Praia de Belas", "cidade": "Porto Alegre", "estado": "RS", "area": 118, "quartos": 3, "banheiros": 3, "vagas": 1, "preco": 658000}
{"logradouro": "Avenida Engenheiro Francisco Rodolfo Simch", "numero": 702, "bairro": "Sarandi", "cidade": "Porto Alegre", "estado": "RS", "area": 62, "quartos": 3, "banheiros": 1, "vagas": 1, "preco": 257000}
{"logradouro": "Rua Itabora\u00ed", "numero": 455, "bairro": "Jardim Bot\u00e2nico", "cidade": "Porto Alegre", "estado": "RS", "area": 69, "quartos": 2, "banheiros": 2, "vagas": 2, "preco": 435000}
{"logradouro": "Avenida Juscelino Kubitschek de Oliveira", "numero": 570, "bairro": "Jardim Leopoldina", "cidade": "Porto Alegre", "estado": "RS", "area": 44, "quartos": 2, "banheiros": 1, "vagas": 1, "preco": 169300}
{"logradouro": "Avenida Manoel Elias", "numero": 2200, "bairro": "Passo das Pedras", "cidade": "Porto Alegre", "estado": "RS", "area": 49, "quartos": 2, "banheiros": 1, "vagas": 1, "preco": 195000}
{"logradouro": "Rua Anita Garibaldi", "numero": 480, "bairro": "Mont' Serrat", "cidade": "Porto Alegre", "estado": "RS", "area": 92, "quartos": 2, "banheiros": 3, "vagas": 1, "preco": 550000}
{"logradouro": "Rua Leopoldo Bier", "numero": 461, "bairro": "Santana", "cidade": "Porto Alegre", "estado": "RS", "area": 55, "quartos": 2, "banheiros": 1, "vagas": 1, "preco": 430000}
{"logradouro": "Rua Gon\u00e7alves Dias", "numero": 1075, "bairro": "Menino Deus", "cidade": "Porto Alegre", "estado": "RS", "area": 86, "quartos": 3, "banheiros": 3, "vagas": 2, "preco": 920000}
